export const LOAD_ALL_CARS = 'LOAD_ALL_CARS';
export const FETCH_CAR_COLORS = 'FETCH_CAR_COLORS';
export const FETCH_CAR_MANUFACTURERS = 'FETCH_CAR_MANUFACTURERS';
export const FILTER_CARS = 'FILTER_CARS';
export const FETCH_CAR_BY_STOCK_NUMBER = 'FETCH_CAR_BY_STOCK_NUMBER';



